server:
  port: 8848

spring:
  datasource:
    url: jdbc:mysql://159.75.125.254:3306/java_utils?allowMultiQueries=false&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: java_utils
    password: java_utils
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
      enabled: true

#对象存储配置
Minio:
  endPoint: oss.elvesyuki.com
  port: 443
  url: https://oss.elvesyuki.com/
  accessKey: javautils
  secretKey: javautils
  write:
    accessKey: javautils
    secretKey: javautils
  read:
    accessKey: javautils
    secretKey: javautils
  #文件服务器存储路径
  uploadUrl:
    BucketName: java-utils

    #用户模块
    User:
      userAvatarUrl: user/avatar/test/